#!/bin/bash

echo "Running linter..."
docker run \
  --rm \
  -v $PWD:/testplugin \
  -v $PWD/tests:/home \
  "mitermayer/vim-test-bed" \
  yarn --cwd testplugin lint

echo "Running tests..."
docker run \
  --rm \
  -v $PWD:/testplugin \
  -v $PWD/tests:/home \
  "mitermayer/vim-test-bed" \
  yarn --cwd testplugin test
